import type { AmbientAsset, Game, Graph } from '../types'

/**
 * Build-time snapshot of everything the listener needs to know.
 *
 * Generated by `scripts/export_static_snapshot.py` from the local SQLite
 * DB and committed under `frontend/public/data/snapshot.json` on the
 * deploy branch. The Vercel build bundles it as a static asset; the
 * frontend fetches it once at startup in static mode.
 *
 * Shape mirrors the listener-facing API responses so we can share types
 * between HTTP and static code paths. CRUD-only fields (write endpoints)
 * have no equivalent here — the static build is listen-only by design.
 */
export interface Snapshot {
  /** Increment when the shape changes incompatibly. */
  version: 1
  /** ISO timestamp the snapshot was generated. Shown in the UI for trust. */
  exported_at: string
  games: Game[]
  /**
   * Every graph referenced as a `default_graph_id` by one of the games,
   * fully populated with nodes and edges. We deliberately do NOT bundle
   * every graph in the DB — only the listener-reachable ones.
   */
  graphs: Graph[]
  ambient_assets: AmbientAsset[]
}

let _snapshot: Snapshot | null = null
let _loadPromise: Promise<Snapshot> | null = null

/**
 * Load the snapshot bundled with the build. Memoised — subsequent calls
 * return the same Promise. Throws if static mode is active but the
 * snapshot file is missing or malformed (the deploy build is broken in
 * that case, and there's no useful fallback).
 */
export function loadSnapshot(): Promise<Snapshot> {
  if (_snapshot) return Promise.resolve(_snapshot)
  if (_loadPromise) return _loadPromise

  _loadPromise = fetch('/data/snapshot.json')
    .then(r => {
      if (!r.ok) {
        throw new Error(
          `Snapshot fetch failed: /data/snapshot.json (${r.status}). ` +
          `Was the build configured with VITE_STATIC_MODE=true but no ` +
          `snapshot.json present at frontend/public/data/?`
        )
      }
      return r.json() as Promise<Snapshot>
    })
    .then(snap => {
      if (snap.version !== 1) {
        throw new Error(
          `Snapshot version mismatch: expected 1, got ${snap.version}`
        )
      }
      _snapshot = snap
      return snap
    })

  return _loadPromise
}

/** Synchronous accessor — only valid after `loadSnapshot()` has resolved. */
export function getSnapshot(): Snapshot {
  if (!_snapshot) {
    throw new Error('Snapshot not loaded — await loadSnapshot() first')
  }
  return _snapshot
}
